//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst_MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriLogTablosu
    {
        public string KategoriAdi { get; set; }
        public Nullable<System.DateTime> IslemSaati { get; set; }
        public string IslemTuru { get; set; }
    }
}
